version: 1
disable_existing_loggers: False
formatters:
  default:
    # "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    # "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  default_file:
    formatter: default
    class: logging.FileHandler
    filename: "${LOG_PATH:./logs}/default_log.log"
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access_file:
    formatter: default
    class: logging.FileHandler
    filename: "${LOG_PATH:./logs}/access_log.log"
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
      - default_file
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
      - access_file
    propagate: no
root:
  level: DEBUG
  handlers:
    - default
    - default_file
  propagate: yes