# convert this to kubernetes
name: kubernetes-test
version: '1.0'
services:
  server:
    image: daraniel/kubernetes-test-server:latest
    build: src/server
    container_name: fastapi-server
    environment:
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      DATABASE: "./database.db"
    ports:
      - "8000:8000"
#    restart: "no"
    volumes:
      - ./src/server:/app
