apiVersion: v1
kind: Service
metadata:
  name: fastapi-server
spec:
  selector:
    app: fastapi-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30007
#  type: ClusterIP
  type: NodePort
#  type: LoadBalancer
