#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: fastapi-server-claim
#  labels:
#    app: fastapi-server
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Mi
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
        - name: fastapi-server
          image: daraniel/kubernetes-test-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: SECRET_KEY
              value: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: DATABASE_CONNECTION_STRING
              value: "mysql+mysqlconnector://fastapi_user:$(MYSQL_PASSWORD)@fastapi-mysql:3306/fastapi"
#          volumeMounts:
#            - name: fastapi-server-persistent-storage
#              mountPath: ./logs
#      volumes:
#        - name: fastapi-server-persistent-storage
#          persistentVolumeClaim:
#            claimName: fastapi-server-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
spec:
  selector:
    app: fastapi-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30007
  #  type: ClusterIP
  #  type: NodePort
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: fastapi-host.com
      http:
        paths:
          - path: /(/|$)(.*) # or something like /app/v1(/|$)(.*)
            pathType: Prefix
            #            pathType: ImplementationSpecific # There seems to be some bugs with using Prefix. If it causes problems, try this method
            backend:
              service:
                name: fastapi-server
                port:
                  number: 8000
